# Generated by Django 5.2.7 on 2025-10-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Confirmed', 'Confirmed'), ('Dispatched', 'Dispatched'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Order Placed', max_length=50),
        ),
    ]
